<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="distance_lidar" value="0.217" />
    <xacro:property name="diametre_lidar" value="0.068" />
    <xacro:property name="longueur_lidar" value="0.04" />
    <xacro:property name="hauteur_lidar" value="0.169" />
    <xacro:property name="masse_lidar" value="0.1" />

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="${distance_lidar} 0 ${hauteur_lidar}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${diametre_lidar/2}" length="${longueur_lidar}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${diametre_lidar/2}" length="${longueur_lidar}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${masse_lidar}" length="${longueur_lidar}" radius="${diametre_lidar/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>  <!-- true if I want to see the blue lines -->
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>