<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <!-- CHASSIS -->
    <xacro:property name="longueur_robot" value="0.25" />
    <xacro:property name="largeur_robot" value="0.15" />
    <xacro:property name="hauteur_robot" value="0.084" />
    <xacro:property name="distance_cir" value="0.07836" />
    <xacro:property name="masse_robot" value="0.5" />

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${distance_cir} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${longueur_robot/2} 0 ${hauteur_robot/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${longueur_robot} ${largeur_robot} ${hauteur_robot}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="${longueur_robot/2} 0 ${hauteur_robot/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${longueur_robot} ${largeur_robot} ${hauteur_robot}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${masse_robot}" x="${longueur_robot}" y="${largeur_robot}" z="${hauteur_robot}">
            <origin xyz="${longueur_robot/2} 0 ${hauteur_robot/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL -->
    <xacro:property name="distance_cir_roue" value="0.1" />
    <xacro:property name="longueur_roue" value="0.03" />
    <xacro:property name="diametre_roue" value="0.065" />
    <xacro:property name="masse_roue" value="0.1" />

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${distance_cir_roue} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${longueur_roue}" radius="${diametre_roue/2}" />
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${longueur_roue}" radius="${diametre_roue/2}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${masse_roue}" length="${longueur_roue}" radius="${diametre_roue/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- RIGHT WHEEL -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${distance_cir_roue} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${longueur_roue}" radius="${diametre_roue/2}" />
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${longueur_roue}" radius="${diametre_roue/2}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${masse_roue}" length="${longueur_roue}" radius="${diametre_roue/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL -->
    <xacro:property name="diametre_caster" value="${diametre_roue}" />
    <xacro:property name="distance_caster" value="0.20" />
    <xacro:property name="masse_caster" value="0.1" />

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${distance_caster} 0 0" rpy="0 0 0"/>
    </joint> 

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${diametre_caster/2}" />
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${diametre_caster/2}" />
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="${masse_caster}" radius="${diametre_caster/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


</robot>